In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('data.csv')

# Handling with missing data

In [3]:
# Drop id and use dataframe index
df = df.drop("id", axis=1)
df

,full_name,first_name,last_name,email,gender,age
0,Mariel Finnigan,Mariel,Finnigan,mfinnigan0@usda.gov,Female,60
1,Kenyon Possek,Kenyon,Possek,kpossek1@ucoz.com,Male,12
2,Lalo Manifould,Lalo,Manifould,lmanifould2@pbs.org,Male,26
3,Nickola Carous,Nickola,Carous,ncarous3@phoca.cz,Male,4
4,Norman Dubbin,Norman,Dubbin,ndubbin4@wikipedia.org,Male,17
5,Hasty Perdue,Hasty,Perdue,hperdue5@qq.com,NaN,77
6,Franz Castello,Franz,Castello,fcastello6@1688.com,Male,25
7,Jorge Tarney,Jorge,Tarney,jtarney7@ft.com,Male,77
8,Eunice Blakebrough,Eunice,Blakebrough,eblakebrough8@sohu.com,Female,45
9,Kristopher Frankcombe,Kristopher,Frankcombe,kfrankcombe9@slate.com,Male,old
10,Palm Domotor,Palm,Domotor,pdomotora@github.io,Male,6
11,Luz Lansdowne,Luz,Lansdowne,llansdowneb@theguardian.com,Female,16
12,Modestia Keble,Modestia,Keble,mkeblec@cmu.edu,Female,91
13,Stacee Bovis,Stacee,Bovis,sbovisd@webeden.co.uk,Female,22
14,Eden Wace,Eden,Wace,ewacee@marriott.com,Female,16
15,Eden Wace,Eden,Wace,ewacee@marriott.com,Female,16
16,Tobias Sherburn,Tobias,Sherburn,tsherburnf@facebook.com,Male,2
17,NaN,NaN,NaN,NaN,NaN,NaN
18,Clair Skillern,Clair,Skillern,cskillerng@nih.gov,Male,-78
19,Mathew Addicott,Mathew,Addicott,maddicotth@acquirethisname.com,Male,65
20,Kerianne Goacher,Kerianne,Goacher,NaN,Female,45
21,Maurits Shawl,Maurits,Shawl,mshawlj@dmoz.org,Male,72
22,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
# Drop all columns where all values NaN
df = df.dropna(how='all')
df

,full_name,first_name,last_name,email,gender,age
0,Mariel Finnigan,Mariel,Finnigan,mfinnigan0@usda.gov,Female,60
1,Kenyon Possek,Kenyon,Possek,kpossek1@ucoz.com,Male,12
2,Lalo Manifould,Lalo,Manifould,lmanifould2@pbs.org,Male,26
3,Nickola Carous,Nickola,Carous,ncarous3@phoca.cz,Male,4
4,Norman Dubbin,Norman,Dubbin,ndubbin4@wikipedia.org,Male,17
5,Hasty Perdue,Hasty,Perdue,hperdue5@qq.com,NaN,77
6,Franz Castello,Franz,Castello,fcastello6@1688.com,Male,25
7,Jorge Tarney,Jorge,Tarney,jtarney7@ft.com,Male,77
8,Eunice Blakebrough,Eunice,Blakebrough,eblakebrough8@sohu.com,Female,45
9,Kristopher Frankcombe,Kristopher,Frankcombe,kfrankcombe9@slate.com,Male,old
10,Palm Domotor,Palm,Domotor,pdomotora@github.io,Male,6
11,Luz Lansdowne,Luz,Lansdowne,llansdowneb@theguardian.com,Female,16
12,Modestia Keble,Modestia,Keble,mkeblec@cmu.edu,Female,91
13,Stacee Bovis,Stacee,Bovis,sbovisd@webeden.co.uk,Female,22
14,Eden Wace,Eden,Wace,ewacee@marriott.com,Female,16
15,Eden Wace,Eden,Wace,ewacee@marriott.com,Female,16
16,Tobias Sherburn,Tobias,Sherburn,tsherburnf@facebook.com,Male,2
18,Clair Skillern,Clair,Skillern,cskillerng@nih.gov,Male,-78
19,Mathew Addicott,Mathew,Addicott,maddicotth@acquirethisname.com,Male,65
20,Kerianne Goacher,Kerianne,Goacher,NaN,Female,45
21,Maurits Shawl,Maurits,Shawl,mshawlj@dmoz.org,Male,72

In [5]:
# Drop Duplicate Content (Eden Wace)
df = df.drop_duplicates()
df = df.reset_index(drop=True)
df

,full_name,first_name,last_name,email,gender,age
0,Mariel Finnigan,Mariel,Finnigan,mfinnigan0@usda.gov,Female,60
1,Kenyon Possek,Kenyon,Possek,kpossek1@ucoz.com,Male,12
2,Lalo Manifould,Lalo,Manifould,lmanifould2@pbs.org,Male,26
3,Nickola Carous,Nickola,Carous,ncarous3@phoca.cz,Male,4
4,Norman Dubbin,Norman,Dubbin,ndubbin4@wikipedia.org,Male,17
5,Hasty Perdue,Hasty,Perdue,hperdue5@qq.com,NaN,77
6,Franz Castello,Franz,Castello,fcastello6@1688.com,Male,25
7,Jorge Tarney,Jorge,Tarney,jtarney7@ft.com,Male,77
8,Eunice Blakebrough,Eunice,Blakebrough,eblakebrough8@sohu.com,Female,45
9,Kristopher Frankcombe,Kristopher,Frankcombe,kfrankcombe9@slate.com,Male,old
10,Palm Domotor,Palm,Domotor,pdomotora@github.io,Male,6
11,Luz Lansdowne,Luz,Lansdowne,llansdowneb@theguardian.com,Female,16
12,Modestia Keble,Modestia,Keble,mkeblec@cmu.edu,Female,91
13,Stacee Bovis,Stacee,Bovis,sbovisd@webeden.co.uk,Female,22
14,Eden Wace,Eden,Wace,ewacee@marriott.com,Female,16
15,Tobias Sherburn,Tobias,Sherburn,tsherburnf@facebook.com,Male,2
16,Clair Skillern,Clair,Skillern,cskillerng@nih.gov,Male,-78
17,Mathew Addicott,Mathew,Addicott,maddicotth@acquirethisname.com,Male,65
18,Kerianne Goacher,Kerianne,Goacher,NaN,Female,45
19,Maurits Shawl,Maurits,Shawl,mshawlj@dmoz.org,Male,72

In [6]:
# Age
# Check if there is a number or other things 
c=0
for row in df['age']:
    try:
        int(row)
        # Check if Age is older than 0
        if (int(row) < 0):
            df.loc[c, 'age']=np.nan
    except ValueError:
        # If no number change to NaN
        df.loc[c, 'age']=np.nan
        pass
   
    c+=1

# Age (Missing Age => old and minus Age)
# Fill the NaN with the Median in the age column
df['age'] = df['age'].fillna(int(df['age'].median()))
df

,full_name,first_name,last_name,email,gender,age
0,Mariel Finnigan,Mariel,Finnigan,mfinnigan0@usda.gov,Female,60
1,Kenyon Possek,Kenyon,Possek,kpossek1@ucoz.com,Male,12
2,Lalo Manifould,Lalo,Manifould,lmanifould2@pbs.org,Male,26
3,Nickola Carous,Nickola,Carous,ncarous3@phoca.cz,Male,4
4,Norman Dubbin,Norman,Dubbin,ndubbin4@wikipedia.org,Male,17
5,Hasty Perdue,Hasty,Perdue,hperdue5@qq.com,NaN,77
6,Franz Castello,Franz,Castello,fcastello6@1688.com,Male,25
7,Jorge Tarney,Jorge,Tarney,jtarney7@ft.com,Male,77
8,Eunice Blakebrough,Eunice,Blakebrough,eblakebrough8@sohu.com,Female,45
9,Kristopher Frankcombe,Kristopher,Frankcombe,kfrankcombe9@slate.com,Male,25
10,Palm Domotor,Palm,Domotor,pdomotora@github.io,Male,6
11,Luz Lansdowne,Luz,Lansdowne,llansdowneb@theguardian.com,Female,16
12,Modestia Keble,Modestia,Keble,mkeblec@cmu.edu,Female,91
13,Stacee Bovis,Stacee,Bovis,sbovisd@webeden.co.uk,Female,22
14,Eden Wace,Eden,Wace,ewacee@marriott.com,Female,16
15,Tobias Sherburn,Tobias,Sherburn,tsherburnf@facebook.com,Male,2
16,Clair Skillern,Clair,Skillern,cskillerng@nih.gov,Male,25
17,Mathew Addicott,Mathew,Addicott,maddicotth@acquirethisname.com,Male,65
18,Kerianne Goacher,Kerianne,Goacher,NaN,Female,45
19,Maurits Shawl,Maurits,Shawl,mshawlj@dmoz.org,Male,72

In [7]:
# Gender
# Change missing gender to Other
df = df.fillna(value={'gender':'Other', 'email':' '})
df

,full_name,first_name,last_name,email,gender,age
0,Mariel Finnigan,Mariel,Finnigan,mfinnigan0@usda.gov,Female,60
1,Kenyon Possek,Kenyon,Possek,kpossek1@ucoz.com,Male,12
2,Lalo Manifould,Lalo,Manifould,lmanifould2@pbs.org,Male,26
3,Nickola Carous,Nickola,Carous,ncarous3@phoca.cz,Male,4
4,Norman Dubbin,Norman,Dubbin,ndubbin4@wikipedia.org,Male,17
5,Hasty Perdue,Hasty,Perdue,hperdue5@qq.com,Other,77
6,Franz Castello,Franz,Castello,fcastello6@1688.com,Male,25
7,Jorge Tarney,Jorge,Tarney,jtarney7@ft.com,Male,77
8,Eunice Blakebrough,Eunice,Blakebrough,eblakebrough8@sohu.com,Female,45
9,Kristopher Frankcombe,Kristopher,Frankcombe,kfrankcombe9@slate.com,Male,25
10,Palm Domotor,Palm,Domotor,pdomotora@github.io,Male,6
11,Luz Lansdowne,Luz,Lansdowne,llansdowneb@theguardian.com,Female,16
12,Modestia Keble,Modestia,Keble,mkeblec@cmu.edu,Female,91
13,Stacee Bovis,Stacee,Bovis,sbovisd@webeden.co.uk,Female,22
14,Eden Wace,Eden,Wace,ewacee@marriott.com,Female,16
15,Tobias Sherburn,Tobias,Sherburn,tsherburnf@facebook.com,Male,2
16,Clair Skillern,Clair,Skillern,cskillerng@nih.gov,Male,25
17,Mathew Addicott,Mathew,Addicott,maddicotth@acquirethisname.com,Male,65
18,Kerianne Goacher,Kerianne,Goacher,,Female,45
19,Maurits Shawl,Maurits,Shawl,mshawlj@dmoz.org,Male,72